import { PrismaClient } from "../src/generated/prisma";

const prisma = new PrismaClient();

const products = [
  {
    barcode: "7790895000812",
    name: "Coca-Cola",
    brand: "Coca-Cola",
    category: "Bebidas",
    score: 12,
    rating: "Malo",
    novaGroup: 4,
    excessSugar: true,
    excessSodium: false,
    excessFat: false,
    excessSaturatedFat: false,
    excessCalories: true,
    nutrition: {
      calories: 42,
      totalFat: 0,
      saturatedFat: 0,
      sodium: 4,
      totalCarbs: 10.6,
      sugars: 10.6,
      fiber: 0,
      protein: 0,
    },
    ingredients: [
      { name: "Agua carbonatada", riskLevel: "safe" },
      { name: "Azúcar", riskLevel: "risky" },
      { name: "Colorante caramelo IV", riskLevel: "moderate" },
      { name: "Ácido fosfórico", riskLevel: "moderate" },
      { name: "Saborizantes naturales", riskLevel: "safe" },
      { name: "Cafeína", riskLevel: "moderate" },
    ],
  },
  {
    barcode: "7622300124364",
    name: "Galletitas Variedad",
    brand: "Terrabusi",
    category: "Galletitas",
    score: 22,
    rating: "Malo",
    novaGroup: 4,
    excessSugar: true,
    excessSodium: false,
    excessFat: false,
    excessSaturatedFat: true,
    excessCalories: true,
    nutrition: {
      calories: 480,
      totalFat: 20,
      saturatedFat: 10,
      sodium: 350,
      totalCarbs: 68,
      sugars: 24,
      fiber: 2,
      protein: 6,
    },
    ingredients: [
      { name: "Harina de trigo", riskLevel: "safe" },
      { name: "Azúcar", riskLevel: "risky" },
      { name: "Grasa vegetal", riskLevel: "risky" },
      { name: "Jarabe de maíz de alta fructosa", riskLevel: "risky" },
      { name: "Leche en polvo", riskLevel: "safe" },
      { name: "Cacao", riskLevel: "safe" },
      { name: "Lecitina de soja", riskLevel: "safe" },
      { name: "Sal", riskLevel: "moderate" },
      { name: "Saborizantes artificiales", riskLevel: "moderate" },
      { name: "TBHQ", riskLevel: "risky" },
    ],
  },
  {
    barcode: "7793940100011",
    name: "Leche Entera",
    brand: "La Serenísima",
    category: "Lácteos",
    score: 78,
    rating: "Excelente",
    novaGroup: 1,
    excessSugar: false,
    excessSodium: false,
    excessFat: false,
    excessSaturatedFat: false,
    excessCalories: false,
    nutrition: {
      calories: 61,
      totalFat: 3.1,
      saturatedFat: 2,
      sodium: 48,
      totalCarbs: 4.7,
      sugars: 4.7,
      fiber: 0,
      protein: 3.1,
    },
    ingredients: [{ name: "Leche entera", riskLevel: "safe" }],
  },
  {
    barcode: "7790310980019",
    name: "Papas Clásicas",
    brand: "Lay's",
    category: "Snacks",
    score: 28,
    rating: "Mediocre",
    novaGroup: 4,
    excessSugar: false,
    excessSodium: true,
    excessFat: true,
    excessSaturatedFat: false,
    excessCalories: true,
    nutrition: {
      calories: 536,
      totalFat: 35,
      saturatedFat: 10,
      sodium: 550,
      totalCarbs: 50,
      sugars: 1,
      fiber: 4,
      protein: 7,
    },
    ingredients: [
      { name: "Papas", riskLevel: "safe" },
      { name: "Aceite vegetal", riskLevel: "moderate" },
      { name: "Sal", riskLevel: "moderate" },
      { name: "Dextrosa", riskLevel: "moderate" },
    ],
  },
  {
    barcode: "7790580511609",
    name: "Bon o Bon",
    brand: "Arcor",
    category: "Golosinas",
    score: 8,
    rating: "Malo",
    novaGroup: 4,
    excessSugar: true,
    excessSodium: false,
    excessFat: false,
    excessSaturatedFat: true,
    excessCalories: true,
    nutrition: {
      calories: 540,
      totalFat: 33,
      saturatedFat: 18,
      sodium: 80,
      totalCarbs: 55,
      sugars: 48,
      fiber: 2,
      protein: 7,
    },
    ingredients: [
      { name: "Azúcar", riskLevel: "risky" },
      { name: "Grasa vegetal hidrogenada", riskLevel: "risky" },
      { name: "Maní", riskLevel: "safe" },
      { name: "Cacao en polvo", riskLevel: "safe" },
      { name: "Leche en polvo", riskLevel: "safe" },
      { name: "Suero de leche", riskLevel: "safe" },
      { name: "Lecitina de soja", riskLevel: "safe" },
      { name: "Saborizantes artificiales", riskLevel: "moderate" },
      { name: "TBHQ", riskLevel: "risky" },
    ],
  },
  {
    barcode: "7792798000012",
    name: "Cerveza Quilmes",
    brand: "Quilmes",
    category: "Bebidas",
    score: 20,
    rating: "Malo",
    novaGroup: 4,
    excessSugar: false,
    excessSodium: false,
    excessFat: false,
    excessSaturatedFat: false,
    excessCalories: true,
    nutrition: {
      calories: 42,
      totalFat: 0,
      saturatedFat: 0,
      sodium: 4,
      totalCarbs: 3.5,
      sugars: 0,
      fiber: 0,
      protein: 0.3,
    },
    ingredients: [
      { name: "Agua", riskLevel: "safe" },
      { name: "Malta de cebada", riskLevel: "safe" },
      { name: "Lúpulo", riskLevel: "safe" },
      { name: "Levadura", riskLevel: "safe" },
      { name: "Antioxidante INS 316", riskLevel: "moderate" },
    ],
  },
  {
    barcode: "7795445000019",
    name: "Pan Lactal Blanco",
    brand: "Bimbo",
    category: "Panificados",
    score: 42,
    rating: "Mediocre",
    novaGroup: 4,
    excessSugar: false,
    excessSodium: true,
    excessFat: false,
    excessSaturatedFat: false,
    excessCalories: false,
    nutrition: {
      calories: 260,
      totalFat: 3,
      saturatedFat: 1,
      sodium: 500,
      totalCarbs: 50,
      sugars: 6,
      fiber: 3,
      protein: 8,
    },
    ingredients: [
      { name: "Harina de trigo", riskLevel: "safe" },
      { name: "Agua", riskLevel: "safe" },
      { name: "Azúcar", riskLevel: "moderate" },
      { name: "Levadura", riskLevel: "safe" },
      { name: "Aceite vegetal", riskLevel: "moderate" },
      { name: "Sal", riskLevel: "moderate" },
      { name: "Gluten de trigo", riskLevel: "safe" },
      { name: "Propionato de calcio", riskLevel: "moderate" },
      { name: "Lecitina de soja", riskLevel: "safe" },
      { name: "Ácido ascórbico", riskLevel: "safe" },
    ],
  },
  {
    barcode: "7793940500190",
    name: "Yogur Vainilla",
    brand: "La Serenísima",
    category: "Lácteos",
    score: 52,
    rating: "Bueno",
    novaGroup: 4,
    excessSugar: true,
    excessSodium: false,
    excessFat: false,
    excessSaturatedFat: false,
    excessCalories: false,
    nutrition: {
      calories: 92,
      totalFat: 2.8,
      saturatedFat: 1.8,
      sodium: 55,
      totalCarbs: 14,
      sugars: 13,
      fiber: 0,
      protein: 3.5,
    },
    ingredients: [
      { name: "Leche parcialmente descremada", riskLevel: "safe" },
      { name: "Azúcar", riskLevel: "risky" },
      { name: "Almidón modificado", riskLevel: "moderate" },
      { name: "Saborizante a vainilla", riskLevel: "moderate" },
      { name: "Cultivos lácteos", riskLevel: "safe" },
      { name: "Sorbato de potasio", riskLevel: "moderate" },
    ],
  },
  {
    barcode: "7798085680019",
    name: "Manaos Cola",
    brand: "Manaos",
    category: "Bebidas",
    score: 10,
    rating: "Malo",
    novaGroup: 4,
    excessSugar: true,
    excessSodium: false,
    excessFat: false,
    excessSaturatedFat: false,
    excessCalories: true,
    nutrition: {
      calories: 44,
      totalFat: 0,
      saturatedFat: 0,
      sodium: 10,
      totalCarbs: 11,
      sugars: 11,
      fiber: 0,
      protein: 0,
    },
    ingredients: [
      { name: "Agua carbonatada", riskLevel: "safe" },
      { name: "Azúcar", riskLevel: "risky" },
      { name: "Colorante caramelo IV", riskLevel: "moderate" },
      { name: "Ácido fosfórico", riskLevel: "moderate" },
      { name: "Saborizantes artificiales", riskLevel: "moderate" },
      { name: "Cafeína", riskLevel: "moderate" },
      {
        name: "Edulcorantes: Aspartamo y Acesulfame K",
        riskLevel: "risky",
      },
    ],
  },
  {
    barcode: "7790189003051",
    name: "Alfajor Mixto",
    brand: "Havanna",
    category: "Golosinas",
    score: 18,
    rating: "Malo",
    novaGroup: 4,
    excessSugar: true,
    excessSodium: false,
    excessFat: false,
    excessSaturatedFat: true,
    excessCalories: true,
    nutrition: {
      calories: 450,
      totalFat: 22,
      saturatedFat: 14,
      sodium: 90,
      totalCarbs: 58,
      sugars: 40,
      fiber: 1,
      protein: 6,
    },
    ingredients: [
      { name: "Azúcar", riskLevel: "risky" },
      { name: "Harina de trigo", riskLevel: "safe" },
      { name: "Dulce de leche", riskLevel: "moderate" },
      { name: "Grasa vegetal", riskLevel: "risky" },
      { name: "Cacao en polvo", riskLevel: "safe" },
      { name: "Leche en polvo", riskLevel: "safe" },
      { name: "Huevo", riskLevel: "safe" },
      { name: "Jarabe de glucosa", riskLevel: "risky" },
      { name: "Lecitina de soja", riskLevel: "safe" },
      { name: "Saborizantes", riskLevel: "moderate" },
    ],
  },
];

async function main() {
  console.log("Seeding database...");

  for (const product of products) {
    await prisma.product.upsert({
      where: { barcode: product.barcode },
      update: product,
      create: product,
    });
    console.log(`  Seeded: ${product.name} (${product.brand})`);
  }

  console.log("Seed completed!");
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
